#!/usr/bin/env python

import cv2
import os
import numpy

class args:
    invert = False
    denoise = False
    fullscreen = True
    kernel = False

    warp = False
    camera = 0
    path = None
    
    blockSize = 11
    C = 2
    buff = 20

    frac = 0.3
    threshold1_v = 0
    threshold2_v = 255



if(__name__ == "__main__"):

    save_dir = os.getcwd()
    if(args.path != None):
        save_dir = args.path

    # configuration {

    blockSize = args.blockSize 
    C = args.C
    buff = args.buff

    frac = args.frac 
    threshold1_v = args.threshold1_v 
    threshold2_v = args.threshold2_v 

    # } configuration

    # getting camera {
    if(args.camera == None):
        # by default uses the first camera
        args.camera = 0
    else:
        args.camera = int(args.camera)
    cap = cv2.VideoCapture(args.camera)
    # } getting camera 

    # window for cv {
    cv2.namedWindow('frame' , cv2.WINDOW_NORMAL)
    if(args.fullscreen):
        cv2.setWindowProperty('frame' , cv2.WND_PROP_FULLSCREEN , cv2.WINDOW_FULLSCREEN)
    # } window for cv

    # main loop {

    try:
    
        # points surrounfing the QR code available
        got_points = False
        # points surrounfing the QR code
        pointsglob = None
        # timer to show message
        timer = 0

        m_list = []

        aruco_dict = cv2.aruco.Dictionary_get(cv2.aruco.DICT_4X4_250)
        parameters =  cv2.aruco.DetectorParameters_create()

        while(True):
            # Capture frame-by-frame
            ret, frame = cap.read()

            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            corners, ids, rejectedImgPoints = cv2.aruco.detectMarkers(gray, aruco_dict, parameters=parameters)
            
            if(len(corners) == 4):
                allids = [0 , 1 , 2 , 3]
                pts = [None , None , None , None]
                for i in range(4):
                    if(ids[i][0] <= 3 and ids[i][0] >= 0):
                        pts[ids[i][0]] = [
                                (int(corners[i][0][0][0]) , int(corners[i][0][0][1])) ,
                                (int(corners[i][0][1][0]) , int(corners[i][0][1][1])) ,
                                (int(corners[i][0][2][0]) , int(corners[i][0][2][1])) ,
                                (int(corners[i][0][3][0]) , int(corners[i][0][3][1]))
                                ];

                ok = not None in pts
            
                if(ok):
                    got_points = True
                    pointsglob = pts

            warped = frame

            if(got_points and (not args.warp)):

                src = numpy.array([pointsglob[0][0] , pointsglob[1][1] , pointsglob[3][2] , pointsglob[2][3]] , numpy.float32)
                dst = numpy.array([[frame.shape[1] , frame.shape[0]] , [0.0 , frame.shape[0]] , [0.0 , 0.0] , [frame.shape[1] , 0.0]] , numpy.float32)
                m = cv2.getPerspectiveTransform(src , dst)
                m_list.append(m)
                if(len(m_list) > buff):
                    m_list.pop(0)
                m_avg = numpy.zeros(m.shape , dtype = m.dtype)
                for mm in m_list:
                    m_avg = m_avg + mm

                m_avg = m_avg / float(len(m_list))
                warped = cv2.warpPerspective(frame , m_avg , (frame.shape[1] , frame.shape[0]))


            # Our operations on the frame come here
            if(args.denoise):
                gray = cv2.cvtColor(warped , cv2.COLOR_BGR2GRAY)
                (b, g, r) = cv2.split(warped)
                war1_b = cv2.adaptiveThreshold(b,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY,blockSize,C)
                war1_g = cv2.adaptiveThreshold(g,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY,blockSize,C)
                war1_r = cv2.adaptiveThreshold(r,255,cv2.ADAPTIVE_THRESH_GAUSSIAN_C, cv2.THRESH_BINARY,blockSize,C)
                ret , warped_b = cv2.threshold(b , threshold1_v , threshold2_v , cv2.THRESH_BINARY+cv2.THRESH_OTSU)
                ret , warped_g = cv2.threshold(g , threshold1_v , threshold2_v , cv2.THRESH_BINARY+cv2.THRESH_OTSU)
                ret , warped_r = cv2.threshold(r , threshold1_v , threshold2_v , cv2.THRESH_BINARY+cv2.THRESH_OTSU)
                mean_b = (frac * warped_b + (1.0 - frac) * war1_b).astype(numpy.uint8)
                mean_g = (frac * warped_g + (1.0 - frac) * war1_g).astype(numpy.uint8)
                mean_r = (frac * warped_r + (1.0 - frac) * war1_b).astype(numpy.uint8)
                warped = cv2.merge((mean_b , mean_g , mean_r))
            
            if(args.kernel):
                kernel = numpy.array(
                            [
                                [ 0 , -1 ,  0] ,
                                [-1 ,  5 , -1] ,
                                [ 0 , -1 , 0 ]
                            ]
                        )
                warped = cv2.filter2D(warped , -1 , kernel)

            tosave = warped

            if(args.invert):
                warped = cv2.bitwise_not(warped)

            if(timer < 100):
                warped = cv2.putText(warped , "   [" + str(100-timer).zfill(3) + "] HIT:q(quit),k(sharpening kernel on/off),i(invert on/off),s(save frame)" , (0 , int(0.5 * warped.shape[0])) , cv2.FONT_HERSHEY_PLAIN , 1 , (0 , 0 , 255) , 1)
                timer += 1
            
            # Display the resulting frame
            cv2.imshow('frame',warped)

            key = cv2.waitKey(1)
 
            if(key == ord('q')):
                break
            elif(key == ord('s')):
                maxPng = 0
                for f in os.listdir(save_dir):
                    if(f[-4:] == ".png" and f[:-4].isdigit() and len(f) == 8):
                        if(int(f[:-4]) > maxPng):
                            maxPng = int(f[:-4])
                cv2.imwrite(os.path.join(save_dir , str(maxPng + 1).zfill(4) + ".png") , tosave)
            elif(key == ord('i')):
                args.invert = not args.invert
            elif(key == ord('k')):
                args.kernel = not args.kernel
            elif(ord('a') <= key <= ord('z')):
                timer = 0

# } main loop

    finally:

        cap.release()
        cv2.destroyAllWindows()

